### ISSUE TITLE
Pre-Submission Checklist

### ISSUE THREAD

**Issue by JacksonBurns** [JacksonBurns/astartes#142]
There are a handful of small things we need to have in place for submitting to PyOpenSci (and subsequently JOSS) to save the editors over there having to ask for them:
 - [x] Contributing File - The package has a CONTRIBUTING.md file that details how to install and contribute to the package.
 - [x] Code of Conduct - The package has a Code of Conduct file.
 - [ ] Issue Submission Documentation - All of the information is filled out in the YAML header of the issue (located at the top of the issue template).
